name: SourceHan font ttf

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: false
        default: 'latest'
        # use ${{ github.event.inputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '^3.10.1'

      - name: Build
        run: |
          pip install otf2ttf

          # 思源宋体
          wget https://github.com/adobe-fonts/source-han-serif/releases/latest/download/SourceHanSerifSC.zip
          unzip SourceHanSerifSC.zip
          otf2ttf OTF/SimplifiedChinese/*.otf
          mv OTF/SimplifiedChinese/*.ttf .
          zip -9 -r -UN=UTF8 SourceHanSerifSC.zip *.ttf
          # clean
          rm -rf OTF *.ttf

          # 思源黑体
          wget https://github.com/adobe-fonts/source-han-sans/releases/latest/download/SourceHanSansSC.zip
          unzip SourceHanSansSC.zip
          otf2ttf OTF/SimplifiedChinese/*.otf
          mv OTF/SimplifiedChinese/*.ttf .
          zip -9 -r -UN=UTF8 SourceHanSansSC.zip *.ttf
          # clean
          rm -rf OTF *.ttf

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          tag: $(date +"%Y%m%d")
          token: ${{ secrets.GITHUB_TOKEN }}
